<a href="https://colab.research.google.com/github/amansurkar/Deep-Learning/blob/master/ANN_Business_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
url='https://raw.githubusercontent.com/amansurkar/Deep-Learning/master/ANN/Churn_Modelling.csv'

In [0]:
data = pd.read_csv(url)

In [64]:
data.head(2)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0

[2 rows x 14 columns]

In [0]:
X=data.iloc[:, 3:13].values

In [24]:
X.head(1)

AttributeError: ignored

In [0]:
y=data.iloc[:, 13].values

In [25]:
y.head(2)

AttributeError: ignored

In [26]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [0]:
label_1=LabelEncoder()

In [0]:
X[:, 1]=label_1.fit_transform(X[:,1])

In [31]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
label_2=LabelEncoder()

In [0]:
X[:,2]=label_2.fit_transform(X[:, 2])

In [34]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.compose import ColumnTransformer

In [0]:
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder='passthrough')

In [0]:
X=ct.fit_transform(X)

In [0]:
X=X[:,1:]

In [39]:
X 

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [40]:
X.shape

(10000, 11)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
scaler=StandardScaler()

In [0]:
X_train=scaler.fit_transform(X_train)

In [0]:
X_test=scaler.fit_transform(X_test)

In [47]:
import keras

Using TensorFlow backend.


In [0]:
from keras.models import Sequential

In [0]:
from keras.layers import Dense

In [50]:
classifier=Sequential()

In [51]:
classifier.add(Dense(output_dim=6, init= 'uniform', activation='relu', input_dim=11))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [52]:
classifier.add(Dense(output_dim=6, init= 'uniform', activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [53]:
classifier.add(Dense(output_dim=1, init= 'uniform', activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [54]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [55]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)




Epoch 1/100





8000/8000 [==============================] - 1s 183us/step - loss: 0.4758 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4265 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4203 - acc: 0.8070
Epoch 4/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4172 - acc: 0.8254
Epoch 5/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4150 - acc: 0.8277
Epoch 6/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4137 - acc: 0.8321
Epoch 7/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4124 - acc: 0.8317
Epoch 8/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4111 - acc: 0.8321
Epoch 9/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4101 - acc: 0.8322
Epoch 10/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4089 - acc

In [0]:
y_pred=classifier.predict(X_test)

In [0]:
y_pred= (y_pred>.5)

In [58]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
conf=confusion_matrix(y_test, y_pred)

In [61]:
conf

array([[1551,   44],
       [ 275,  130]])