In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [4]:
X=data.iloc[:, 3:13 ].values

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y=data.iloc[:, 13].values

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
lencoder_1= LabelEncoder()

In [10]:
X[:, 1]=lencoder_1.fit_transform(X[:, 1])

In [11]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [12]:
lencoder_2=LabelEncoder()

In [13]:
X[:, 2]=lencoder_2.fit_transform(X[:,2])

In [14]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
onehotencoder=OneHotEncoder(categorical_features= [1])

In [16]:
X=onehotencoder.fit_transform(X).toarray()

C:\Users\Aman Surkar\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Aman Surkar\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [17]:
X=X[:,1:]

In [18]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [19]:
X.shape

(10000, 11)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler=StandardScaler()

In [24]:
X_train=scaler.fit_transform(X_train)

In [25]:
X_test=scaler.fit_transform(X_test)

In [26]:
import keras

Using TensorFlow backend.


In [27]:
from keras.models import Sequential

In [28]:
from keras.layers import Dense

In [29]:
classifier=Sequential()

In [30]:
classifier.add(Dense(output_dim=6, init= 'uniform', activation='relu', input_dim=11))

C:\Users\Aman Surkar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [31]:
classifier.add(Dense(output_dim=6, init= 'uniform', activation='relu'))

C:\Users\Aman Surkar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [32]:
classifier.add(Dense(output_dim=1, init= 'uniform', activation='sigmoid'))

C:\Users\Aman Surkar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [33]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [34]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 302us/step - loss: 0.5035 - accuracy: 0.7954
Epoch 2/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.4302 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4234 - accuracy: 0.8010
Epoch 4/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.4171 - accuracy: 0.8264
Epoch 5/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4122 - accuracy: 0.8322
Epoch 6/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.4085 - accuracy: 0.8322
Epoch 7/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4058 - accuracy: 0.8347
Epoch 8/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.4040 - accuracy: 0.8322
Epoch 9/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.4022 - accuracy: 0.8342
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 2s 206us/step - loss: 0.3356 - accuracy: 0.8634
Epoch 78/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.3359 - accuracy: 0.8630
Epoch 79/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.3356 - accuracy: 0.8630
Epoch 80/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.3358 - accuracy: 0.8593
Epoch 81/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.3358 - accuracy: 0.8625
Epoch 82/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3345 - accuracy: 0.8629
Epoch 83/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.3351 - accuracy: 0.8629
Epoch 84/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.3349 - accuracy: 0.8630
Epoch 85/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.3349 - accuracy: 0.8629
Epoch 86/100
8000/8000 [==============================] - 2

In [35]:
y_pred=classifier.predict(X_test)

In [36]:
y_pred

array([[0.29504147],
       [0.42085266],
       [0.14048211],
       ...,
       [0.22154382],
       [0.24931328],
       [0.14758104]], dtype=float32)

In [37]:
y_pred= (y_pred>0.5)

In [38]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
conf=confusion_matrix(y_test, y_pred)

In [41]:
conf

array([[1492,  103],
       [ 180,  225]], dtype=int64)